#!/usr/bin/env python3
"""
SYNAPSE-BUS GENESIS GENERATOR
The Master Source Code Generator for Self-Hydrating Repository System

This script implements the "Genesis Architecture" for SynapseBus-Core.
It solves the "Workflow Bottleneck" by creating a Swarm of Agents that:
1. Parse your chat dumps into rigorous blueprints
2. Generate directory trees into reality
3. Auto-populate code using local LLMs

Three AI Engineering Bottleneck Inventions:
- Invention I: "Chat-to-Spec" Ingestion Valve
- Invention II: "Holographic" Docker Hub Methodology
- Invention III: "Synaptic" Knowledge Linker
"""

import os
import yaml
import subprocess
from pathlib import Path

# ==========================================================
# CONFIGURATION: THE LEGION OF MINDS
# ==========================================================
REPO_ROOT = "synapse-bus-core"
BIBLIOGRAPHY_PATH = "./knowledge/bibliography"
DOCKER_HUB_USER = "strategickhaos"

# The Blueprint: Extracted from your Chat Dumps + Ripley Scroll
BLUEPRINT = """
synapse-bus-core:
  - .github:
      workflows:
        - thermodynamics.yaml: "guards: entropy_threshold < 0.8"
        - ripley-gates.yaml: "gates: [calcination, solution, putrefaction]"
  - src:
      claims:
        - gsch_claim8.rs: "ref: INV-076, Patent Claim 8"
      primitives:
        - buffer.flame: "ref: Ripley Gate 2 (Solution)"
        - clamp.flame: "ref: Ripley Gate 3 (Separation)"
      nervous_system:
        - spike.rs: "struct: Spike { vector: PhysicsVector, risk: f32 }"
      organs:
        vision:
          - retina.rs: "tool: nmap_purified, algo: Gravitational Search"
        touch:
          - osteon.rs: "tool: metasploit_purified, algo: Simulated Annealing"
        hearing:
          - cochlea.rs: "tool: wireshark_purified, algo: Optics Optimization"
  - infra:
      k8s:
        - autopilot.yaml: "policy: Request = Limit"
  - docker:
      - compose.yml: "orch: agent_swarm"
  - knowledge:
      bibliography:
        - README.md: "Bibliography reference system"
  - scripts:
      - ingest_chat.py: "Chat-to-Spec Ingestion Valve"
      - hydrate_file.py: "Inline LLM Mason Agent"
"""

def create_structure(base_path, structure):
    """
    Recursive function to build the tree from YAML.
    
    This implements the core of the "Self-Hydrating Repository System".
    Each file is planted as a "seed" with metadata that the Mason agent
    will use to hydrate it with actual code.
    """
    for name, content in structure.items():
        path = os.path.join(base_path, name)
        
        if isinstance(content, dict):
            # It's a directory
            os.makedirs(path, exist_ok=True)
            print(f" [+] Created Directory: {path}")
            create_structure(path, content)
        elif isinstance(content, list):
            # It's a directory with list of items
            os.makedirs(path, exist_ok=True)
            print(f" [+] Created Directory: {path}")
            for item in content:
                if isinstance(item, dict):
                    create_structure(path, item)
                else:
                    # It's a file entry
                    file_path = os.path.join(path, item)
                    plant_seed(file_path, "Generated by Genesis")
        else:
            # It's a file - This is where the Agent comes in
            plant_seed(path, content)

def plant_seed(filepath, metadata):
    """
    Plants a 'seed' file with reference metadata.
    
    The Inline LLM (Mason) will later read this metadata and populate
    the file with actual code by querying the Bibliography.
    """
    # Determine file extension and comment style
    ext = Path(filepath).suffix
    if ext in ['.rs', '.flame']:
        comment_start = '//'
    elif ext in ['.py']:
        comment_start = '#'
    elif ext in ['.yaml', '.yml']:
        comment_start = '#'
    elif ext == '.md':
        comment_start = '<!--'
        comment_end = '-->'
    else:
        comment_start = '//'
    
    # Create parent directory if it doesn't exist
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    
    with open(filepath, 'w') as f:
        if ext == '.md':
            f.write(f"{comment_start} SYNAPSE-BUS GENERATED | REF: {metadata} {comment_end}\n")
        else:
            f.write(f"{comment_start} SYNAPSE-BUS GENERATED | REF: {metadata}\n")
            f.write(f"{comment_start} AWAITING HYDRATION BY MASON AGENT\n")
        
        # Add minimal placeholder content based on file type
        if ext == '.rs':
            f.write(f"\n{comment_start} Rust source - to be generated\n")
        elif ext == '.flame':
            f.write(f"\n{comment_start} FlameLang primitive - to be generated\n")
        elif ext == '.py':
            f.write(f'\n{comment_start} Python source - to be generated\n')
            f.write('"""Module pending hydration"""\n')
        elif ext in ['.yaml', '.yml']:
            f.write(f"\n{comment_start} YAML configuration - to be generated\n")
        elif ext == '.md':
            f.write(f"\n# Documentation\n\nPending hydration by Mason agent.\n")
    
    print(f" [>] Planted Seed: {filepath}")

def summon_agents():
    """
    Generates the Docker Compose to hydrate the repo.
    
    This implements the "Holographic" Docker Hub Methodology (Invention II).
    The agent swarm consists of:
    - architect: Parses chat dumps into blueprints
    - mason: Populates seed files using local LLM
    - builder: Compiles and pushes to Docker Hub with entropy checks
    """
    compose_path = os.path.join(REPO_ROOT, "docker", "compose.yml")
    os.makedirs(os.path.dirname(compose_path), exist_ok=True)
    
    compose_content = f"""# SYNAPSE-BUS AGENT SWARM
# Self-Hydrating Repository System
# Generated by genesis.py

version: '3.8'

services:
  # Invention I: Chat-to-Spec Ingestion Valve
  architect:
    image: python:3.9
    volumes:
      - ./:/repo
      - {BIBLIOGRAPHY_PATH}:/knowledge
    command: python3 /repo/scripts/ingest_chat.py
    environment:
      - BLUEPRINT_PATH=/repo/blueprint.yaml
      - BIBLIOGRAPHY_PATH=/knowledge
    networks:
      - synapsebus
    
  # Invention III: Synaptic Knowledge Linker (The Mason)
  mason:
    image: ollama/ollama:latest  # The Inline LLM (Qwen2.5)
    volumes:
      - ./:/repo
      - {BIBLIOGRAPHY_PATH}:/knowledge
    environment:
      - TARGET_DIR=/repo/src
      - LLM_MODEL=qwen2.5-coder
      - BIBLIOGRAPHY_PATH=/knowledge
    # This agent reads the 'seeds' created by genesis.py and populates code
    # by querying the Bibliography (PDFs/Obsidian).
    command: python3 /repo/scripts/hydrate_file.py
    networks:
      - synapsebus
    depends_on:
      - architect

  # Invention II: Holographic Docker Hub Methodology
  builder:
    image: docker:dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/repo
    environment:
      - HUB_USER={DOCKER_HUB_USER}
      - ENTROPY_THRESHOLD=0.8
      - RIPLEY_GATES=calcination,solution,putrefaction
    # Methodology: Recursive Docker Build -> Entropy Check -> Push to Hub
    command: sh -c "echo 'Builder ready for Dockerization'"
    networks:
      - synapsebus
    depends_on:
      - mason

networks:
  synapsebus:
    driver: bridge
"""
    
    with open(compose_path, 'w') as f:
        f.write(compose_content)
    print(f" [!] Agent Swarm Defined: {compose_path}")

def create_readme():
    """Create README for synapse-bus-core explaining the system."""
    readme_path = os.path.join(REPO_ROOT, "README.md")
    readme_content = """# Synapse-Bus Core

## Self-Hydrating Repository System

This repository was generated by the **Genesis Architecture** system, solving the "Workflow Bottleneck" of pasting huge chats by creating a self-hydrating codebase.

### Three AI Engineering Bottleneck Inventions

#### Invention I: The "Chat-to-Spec" Ingestion Valve
- **The Bottleneck**: Massive chat dumps lose structure in text
- **The Invention**: Parser agent (`ingest_agent`) that regex-matches code blocks and converts to `blueprint.yaml`
- **Cross-references**: Board Meeting 003 notes to map modules to Ripley Gates

#### Invention II: The "Holographic" Docker Hub Methodology
- **The Bottleneck**: Manually building 16+ Docker images is slow
- **The Invention**: Recursive docker-compose strategy where `.flame` files compile to Dockerfiles on-the-fly
- **GSCH Framework**: "Buffer" (absorb build spikes) and "Dissolve" (delete failed artifacts)

#### Invention III: The "Synaptic" Knowledge Linker
- **The Bottleneck**: Empty source files
- **The Invention**: Inline Coding LLM queries uploaded PDFs and auto-generates code based on patent definitions

### Usage

1. **Run Genesis** (already done):
   ```bash
   python3 genesis.py
   ```

2. **Hydrate the Repository**:
   ```bash
   cd synapse-bus-core
   docker-compose -f docker/compose.yml up
   ```

3. **The Agent Swarm will**:
   - Parse chat dumps into `blueprint.yaml`
   - Read seed files with metadata
   - Query Bibliography for knowledge
   - Generate actual source code
   - Build and push Docker images (if entropy < 0.8)

### Directory Structure

```
synapse-bus-core/
├── .github/workflows/       # Thermodynamics & Ripley Gate checks
├── src/
│   ├── claims/             # Patent claim implementations
│   ├── primitives/         # FlameLang buffer/clamp primitives
│   ├── nervous_system/     # Spike routing logic
│   └── organs/             # Vision, Touch, Hearing subsystems
├── infra/k8s/              # Kubernetes autopilot configs
├── docker/                 # Agent swarm orchestration
├── knowledge/bibliography/ # Reference documents and PDFs
└── scripts/                # Ingestion and hydration agents
```

### Entropy Threshold

The system uses **GSCH Entropy** checks to prevent high-complexity code:
- Entropy < 0.8: Code is pushed to Docker Hub
- Entropy >= 0.8: Build artifacts are dissolved (deleted)

### Ripley Gates

All modules pass through alchemical gates:
1. **Calcination**: Initial burn-in testing
2. **Solution**: Buffer/Clamp primitive validation
3. **Putrefaction**: Stress testing and decomposition

---

Generated by StrategicKhaos Genesis System - 880x Cost Reduction via Local-First Architecture
"""
    
    with open(readme_path, 'w') as f:
        f.write(readme_content)
    print(f" [📄] Created README: {readme_path}")

def main():
    """Main execution function."""
    print("=" * 60)
    print("INITIALIZING SYNAPSE-BUS GENESIS")
    print("Self-Hydrating Repository System")
    print("=" * 60)
    
    # Parse the blueprint
    try:
        data = yaml.safe_load(BLUEPRINT)
        print(f"\n [✓] Blueprint parsed successfully")
    except yaml.YAMLError as e:
        print(f"\n [✗] Failed to parse blueprint: {e}")
        return 1
    
    # Create the directory structure
    print(f"\n [→] Creating directory structure...")
    create_structure(".", data)
    
    # Generate agent swarm orchestration
    print(f"\n [→] Summoning agent swarm...")
    summon_agents()
    
    # Create README
    print(f"\n [→] Creating documentation...")
    create_readme()
    
    print("\n" + "=" * 60)
    print("STRUCTURE COMPLETE")
    print("=" * 60)
    print(f"\nNext steps:")
    print(f"  1. cd {REPO_ROOT}")
    print(f"  2. docker-compose -f docker/compose.yml up")
    print(f"  3. Watch the agents hydrate your repository!")
    print("\n" + "=" * 60)
    
    return 0

if __name__ == "__main__":
    exit(main())
