#!/bin/bash
# TRIG6 Phases Script - Run all 6 phases systematically

set -e  # Exit on error

REPO=$(pwd)

echo "╔════════════════════════════════════════════════════════════╗"
echo "║       TRIG6 OMNI CALCULATOR - 6 PHASES EXECUTION          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Phase 1: Display Core Implementation
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 1: Core TRIG6 Implementation (Create)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "File: $REPO/main.py"
echo "Functions: trig6, unit_circle, rolling_offset, omni_calc"
echo ""
cat "$REPO/main.py"
echo ""
echo "Running test..."
python3 "$REPO/main.py"
echo ""
read -p "Press Enter to continue to Phase 2..."
echo ""

# Phase 2: Advanced Vectorized Implementation
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 2: Vectorized Implementation (Evaluate)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Showing vector_trig6 function (batch operations ~10x faster):"
echo ""
grep -A 10 "def vector_trig6" "$REPO/main.py"
echo ""
read -p "Press Enter to continue to Phase 3..."
echo ""

# Phase 3: Benchmarks
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 3: Efficiency Benchmarks (Evaluate)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "File: $REPO/bench.py"
echo "Comparing TRIG6 vs Python/Rust/C++ efficiencies..."
echo ""
python3 "$REPO/bench.py"
echo ""
read -p "Press Enter to continue to Phase 4..."
echo ""

# Phase 4: CLI & Error Handling
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 4: CLI & Error Handling (Create)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "File: $REPO/cli.py"
echo "Testing mathematician CLI tool..."
echo ""
echo "Example 1: θ = π/4"
python3 "$REPO/cli.py" --theta "math.pi/4"
echo ""
echo "Example 2: θ = π/6"
python3 "$REPO/cli.py" --theta "math.pi/6"
echo ""
echo "Error handling (singularity at π/2 is handled with inf):"
python3 "$REPO/cli.py" --theta "math.pi/2" || echo "Note: Singularities handled with infinity values"
echo ""
read -p "Press Enter to continue to Phase 5..."
echo ""

# Phase 5: Q&A Dialog
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 5: Engineering Interview Q&A (Evaluate)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "File: $REPO/qa.md"
echo "Displaying Q&A content (first 50 lines)..."
echo ""
head -n 50 "$REPO/qa.md"
echo ""
echo "... (see qa.md for complete interview dialog)"
echo ""
read -p "Press Enter to continue to Phase 6..."
echo ""

# Phase 6: Summary & Documentation
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 6: Complete Documentation (Create)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Repository Structure:"
echo ""
tree -L 1 "$REPO" 2>/dev/null || find "$REPO" -maxdepth 1 -type f -name "*.py" -o -name "*.md" -o -name "*.txt" -o -name "*.sh" | sort
echo ""
echo "All phases complete!"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║              TRIG6 OMNI CALCULATOR READY                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo "  • Run benchmarks: python bench.py"
echo "  • Use CLI: python cli.py --theta 'math.pi/3'"
echo "  • Review Q&A: cat qa.md"
echo "  • Extend with custom implementations"
echo ""
