// Generated by FlameLang Compiler
// KHAOS Script → FlameIR → Rust

use std::collections::HashMap;

fn main() {
    let mut stack: Vec<i64> = Vec::new();
    let mut vars: HashMap<String, i64> = HashMap::new();
    
    // Instruction 0: LoadString("Hello, FlameLang!")
    // String will be printed by next Print instruction
    stack.push(0); // Placeholder for string "Hello, FlameLang!"
    stack.pop(); // Remove placeholder
    println!("Hello, FlameLang!");
    // Instruction 1: Print
    if let Some(val) = stack.pop() {
        println!("{}", val);
    }
    // Instruction 2: LoadConst(42)
    stack.push(42);
    // Instruction 3: Store("x")
    vars.insert("x".to_string(), stack.pop().unwrap());
    // Instruction 4: Load("x")
    stack.push(*vars.get("x").unwrap());
    // Instruction 5: LoadConst(8)
    stack.push(8);
    // Instruction 6: Add
    let b = stack.pop().unwrap();
    let a = stack.pop().unwrap();
    stack.push(a + b);
    // Instruction 7: Store("y")
    vars.insert("y".to_string(), stack.pop().unwrap());
    // Instruction 8: Load("y")
    stack.push(*vars.get("y").unwrap());
    // Instruction 9: Print
    if let Some(val) = stack.pop() {
        println!("{}", val);
    }
    // Instruction 10: Halt
    // Program halted
}
