#!/usr/bin/env python3
"""
BOARD-31 Mobius Compiler — ASSERT equations → executable Python test functions.

Parses: if(CONDITION) when(TRIGGER) then(ACTION)
Compiles each ASSERT into a callable test(event: dict) -> bool
Writes compiled_tests.py to reports/
"""

from __future__ import annotations
import re, sys
from pathlib import Path

BOARD_ROOT = Path(__file__).resolve().parents[1]

# Known antibody action map
ANTIBODY_ACTIONS = {
    "fire_antibody":   lambda ab, ev: True,   # always fires if condition met
    "open_case":       lambda ab, ev: True,
    "log_only":        lambda ab, ev: False,   # non-escalating
}

# Known condition evaluators
def _eval_condition(cond: str, event: dict) -> bool:
    cond = cond.strip()
    # token_in_url
    if "token_in_url" in cond:
        url = event.get("url", "")
        return any(p in url for p in ("access_token=", "id_token=", "bearer=", "auth_token="))
    # browser_nav
    if "browser_nav" in cond:
        return event.get("type") in ("navigation", "webrequest", "url_change")
    # severity == CRITICAL
    m = re.match(r"severity\s*==\s*(\w+)", cond)
    if m:
        return event.get("severity") == m.group(1)
    # cpu_load > threshold
    m = re.match(r"(\w+)\s*([><=!]+)\s*([\d.]+)", cond)
    if m:
        field, op, val = m.groups()
        ev_val = event.get(field)
        if ev_val is None:
            return False
        try:
            ev_val = float(ev_val)
            val    = float(val)
            return eval(f"{ev_val} {op} {val}")  # noqa: S307 — controlled input
        except Exception:
            return False
    return False


def compile_assert(equation) -> dict:
    """Compile a single ASSERT equation into a test function + metadata."""
    args = equation.args if hasattr(equation, "args") else equation.get("args", [])
    body = equation.body if hasattr(equation, "body") else equation.get("body", "")
    name = equation.name if hasattr(equation, "name") else equation.get("name", "assert")

    # Extract if/when/then from args list
    # ASSERT: if(CONDITION) when(TRIGGER) then(ACTION ANTIBODY_NAME)
    if_cond  = str(args[0]) if len(args) > 0 else body
    when_tri = str(args[1]) if len(args) > 1 else "always"
    then_act = str(args[2]) if len(args) > 2 else "log_only"

    def test(event: dict) -> bool:
        cond_hit    = _eval_condition(if_cond, event)
        trigger_hit = _eval_condition(when_tri, event) if when_tri != "always" else True
        return cond_hit and trigger_hit

    return {
        "name":      name,
        "if":        if_cond,
        "when":      when_tri,
        "then":      then_act,
        "test":      test,
        "source":    equation,
    }


def compile_ast(ast) -> list[dict]:
    equations = ast.equations if hasattr(ast, "equations") else []
    compiled  = []
    for eq in equations:
        kind = eq.kind if hasattr(eq, "kind") else eq.get("kind", "")
        if kind == "ASSERT":
            compiled.append(compile_assert(eq))
    return compiled


def run_tests(compiled: list[dict], sample_events: list[dict]) -> list[dict]:
    results = []
    for ct in compiled:
        fn      = ct["test"]
        passed  = sum(1 for ev in sample_events if fn(ev))
        results.append({
            "name":   ct["name"],
            "if":     ct["if"],
            "when":   ct["when"],
            "then":   ct["then"],
            "events_tested": len(sample_events),
            "events_fired":  passed,
            "status": "PASS" if passed > 0 else "WARN",
        })
    return results


def write_compiled_tests(compiled: list[dict], out: Path):
    lines = [
        "# Auto-generated by BOARD-31 compiler.py",
        "# DO NOT EDIT — regenerate with: python src/compiler.py",
        "",
    ]
    for ct in compiled:
        fn_name = re.sub(r"\W+", "_", ct["name"]).lower()
        lines += [
            f"def test_{fn_name}(event: dict) -> bool:",
            f"    # if({ct['if']}) when({ct['when']}) then({ct['then']})",
            f"    from src.compiler import _eval_condition",
            f"    cond = _eval_condition({ct['if']!r}, event)",
            f"    trig = _eval_condition({ct['when']!r}, event) if {ct['when']!r} != 'always' else True",
            f"    return cond and trig",
            "",
        ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"  Compiled tests → {out}")


SAMPLE_EVENTS = [
    {"type": "navigation", "url": "https://app.example.com/callback?access_token=abc123",
     "severity": "CRITICAL"},
    {"type": "console_error", "url": "https://app.example.com/dashboard",
     "severity": "LOW"},
    {"type": "webrequest",  "url": "https://app.example.com/api",
     "severity": "MEDIUM", "cpu_load": 0.55},
]


if __name__ == "__main__":
    sys.path.insert(0, str(BOARD_ROOT / "src"))
    from parser import parse_file
    mobius   = sys.argv[1] if len(sys.argv) > 1 else \
               str(BOARD_ROOT / "cellphones" / "5127739959" / "equations.mobius")
    ast      = parse_file(mobius)
    compiled = compile_ast(ast)
    results  = run_tests(compiled, SAMPLE_EVENTS)

    write_compiled_tests(compiled, BOARD_ROOT / "reports" / "compiled_tests.py")

    print(f"\n  {len(compiled)} ASSERT equations compiled")
    for r in results:
        sym = "✓" if r["status"] == "PASS" else "⚠"
        print(f"  {sym} {r['name']:<30} fired={r['events_fired']}/{r['events_tested']}")
