[package]
name = "sagco_formula_compiler"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sagco_formula_compiler"
path = "src/main.rs"

[lib]
name = "sagco_formula_compiler"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
clap = { version = "4", features = ["derive"] }
thiserror = "1"
