#!/usr/bin/env python3
"""
BOARD-32 Portfolio Publisher

Harvests ERU artifacts from every board and renders:
  - case-studies/*.md          one per major proof
  - resume-bullets/*.md        STAR-format bullets
  - portfolio_index.md         master landing page

Usage:
  python portfolio_builder.py --build          full build
  python portfolio_builder.py --case-studies   only case studies
  python portfolio_builder.py --resume         only resume bullets
  python portfolio_builder.py --index          only index
  python portfolio_builder.py --list           list all source artifacts
"""

from __future__ import annotations
import json, yaml, sys, datetime
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
BOARD     = REPO_ROOT / "BOARD-32-PORTFOLIO-PUBLISHER"
OUT_CASES = BOARD / "case-studies"
OUT_RESUME= BOARD / "resume-bullets"
OUT_RPT   = BOARD / "reports"

NOW = datetime.date.today().isoformat()


# ── Source harvesters ─────────────────────────────────────────────────────────

def _load_yaml(p: Path) -> dict:
    try:
        return yaml.safe_load(p.read_text()) or {}
    except Exception:
        return {}

def _load_json(p: Path) -> Any:
    try:
        return json.loads(p.read_text())
    except Exception:
        return {}


def harvest_inventions() -> list[dict]:
    seeds_dir = REPO_ROOT / "MISSING-LINKS" / "seeds"
    return [_load_yaml(f) for f in sorted(seeds_dir.glob("*.yaml"))] if seeds_dir.exists() else []


def harvest_closed_cases() -> list[dict]:
    dirs = [
        REPO_ROOT / "MISSING-LINKS" / "cases" / "closed",
        REPO_ROOT / "BOARD-26-REMEDIATION-ENGINE" / "cases" / "closed",
    ]
    cases = []
    for d in dirs:
        if d.exists():
            cases += [_load_yaml(f) for f in sorted(d.glob("*.yaml"))]
    return cases


def harvest_eru_cases() -> list[dict]:
    sources = [
        REPO_ROOT / "BOARD-21-PHYSICS-FLEET" / "reports",
        REPO_ROOT / "BOARD-24-GCP-MASTERY" / "eru",
        REPO_ROOT / "BOARD-31-CELLPHONE-MOBIUS-LAB" / "reports",
    ]
    cases = []
    for d in sources:
        if d.exists():
            for f in sorted(d.glob("*.yaml")):
                data = _load_yaml(f)
                if data:
                    data["_source"] = str(f.relative_to(REPO_ROOT))
                    cases.append(data)
    return cases


def harvest_certs() -> list[dict]:
    cert_dir = REPO_ROOT / "BOARD-10-UNIVERSITY" / "certificates"
    return [_load_yaml(f) for f in sorted(cert_dir.glob("*.yaml"))] if cert_dir.exists() else []


def harvest_antibodies() -> list[dict]:
    ab_dir = REPO_ROOT / "BOARD-11-ANTIBODIES" / "antibodies"
    return [_load_yaml(f) for f in sorted(ab_dir.glob("*.yaml"))] if ab_dir.exists() else []


# ── Case study renderer ───────────────────────────────────────────────────────

def render_invention_case_study(seed: dict) -> str:
    title    = seed.get("title", "Unnamed Invention")
    inv      = seed.get("invention", {})
    inv_name = inv.get("name", title) if isinstance(inv, dict) else title
    law      = seed.get("law", "")
    boards   = (inv.get("boards_affected", []) if isinstance(inv, dict) else [])

    return f"""# Case Study: {inv_name}

**Date:** {seed.get('created', NOW)}
**District:** {seed.get('district', '?')}
**Boards:** {', '.join(boards) if boards else 'SAGCO-OS'}
**PMI Delta:** {seed.get('pmi_delta_estimate', '?')}

## ERU Loop

| Field | Value |
|-------|-------|
| **Expected** | {seed.get('expected', '?')} |
| **Actual** | {seed.get('actual', '?')} |
| **Variance** | {seed.get('variance', '?')} |

## Contradiction

{seed.get('contradiction', {}).get('description', seed.get('variance', '')) if isinstance(seed.get('contradiction'), dict) else ''}

**Invariant violated:** `{seed.get('invariant_violated', '?')}` — {law}

## Understanding

{seed.get('understanding', '').strip()}

## Invention

**{inv_name}**

{inv.get('description', '') if isinstance(inv, dict) else ''}

### Prototype Tasks

{chr(10).join(f'- {t}' for t in (inv.get('prototype_task', '').splitlines() if isinstance(inv, dict) else [])) or '- See seed file'}

## Verification

{chr(10).join(f'- {t}' for t in (seed.get('verification', {}).get('test_cases', []) if isinstance(seed.get('verification'), dict) else []))}

---
*Generated by BOARD-32-PORTFOLIO-PUBLISHER — SAGCO-OS*
"""


def render_gke_case_study(case: dict) -> str:
    title   = case.get("title", case.get("case_id", "ERU Case"))
    physics = case.get("physics_law", "")
    return f"""# Case Study: {title}

**Source:** `{case.get('_source', '?')}`
**Severity:** {case.get('severity', '?')}
**Physics Law:** {physics}

## ERU Loop

| Field | Value |
|-------|-------|
| **Expected** | {case.get('expected', '?')} |
| **Actual** | {case.get('actual', '?')} |
| **Variance** | {case.get('variance', '?')} |

## Understanding

{case.get('understanding', case.get('resolution', ''))}

## Proof

{case.get('proof', case.get('antibody', ''))}

---
*Generated by BOARD-32-PORTFOLIO-PUBLISHER — SAGCO-OS*
"""


# ── Resume bullet renderer ────────────────────────────────────────────────────

def render_resume_bullets(inventions: list, certs: list, antibodies: list, boards: list) -> str:
    bullets = []

    if inventions:
        bullets.append(
            f"- Designed and implemented **Payload-Aware Antibody Router** "
            f"(SAGCO-OS MISSING-LINKS substrate); identified invariant violation "
            f"across 3 boards; estimated PMI delta +0.08"
        )

    if len(antibodies) >= 5:
        bullets.append(
            f"- Built **{len(antibodies)}-rule browser security antibody library** "
            f"(BOARD-11-ANTIBODIES); classifies CRITICAL token leaks, PII tracking "
            f"pixel exposure, and third-party widget noise with zero false positives"
        )

    if any("BOARD-24" in b for b in boards):
        bullets.append(
            "- Architected **GKE sovereign cluster** with NetworkPolicy, "
            "ResourceQuota, Workload Identity, and PodDisruptionBudget; "
            "mapped to 4 ERU physics laws (GKE-ERU-001 through 004)"
        )

    if any("BOARD-31" in b for b in boards):
        bullets.append(
            "- Built **Mobius Calculus DSL compiler** (BOARD-31) with lexer, "
            "parser, AST-to-Excel renderer, ERU runner, and assertion compiler; "
            "bridges academic calculus homework to structured ERU case studies"
        )

    if any("BOARD-26" in b for b in boards):
        bullets.append(
            "- Implemented **self-improving remediation loop** (BOARD-26): "
            "contradiction → case → remediate → verify → PMI↑ → invention; "
            "eliminates human-in-the-loop bottleneck for recurring variances"
        )

    if any("BOARD-29" in b for b in boards):
        bullets.append(
            "- Designed **SAGCO Phone OS** (BOARD-29): desktop folder = device, "
            "files = signals; full lexer → parser → AST → citizen registration "
            "pipeline; every agent assigned E.164 + sagco:// internal line"
        )

    if len(certs) >= 1:
        bullets.append(
            f"- Achieved **SAGCO Sovereign Organism Certification** "
            f"(BOARD-10-UNIVERSITY) across {len(certs)} exam cycles; "
            f"organism grades: brick health, security ERU, net scan, physics fleet, "
            f"citizens, inventions"
        )

    bullets.append(
        "- Engineered **31-board SAGCO-OS** sovereign architecture stack: "
        "agents, citizens, antibodies, PMI scoring, phone OS, Mobius compiler, "
        "GKE cluster, Firefox extension, and MISSING-LINKS invention substrate — "
        "all wired through a unified `sagco` CLI dispatcher"
    )

    return f"""# Distinguished Engineer Resume Bullets

**Domenic Garza — Node 137 — Strategickhaos DAO LLC**
**Generated:** {NOW}

## Engineering Achievements (SAGCO-OS)

{chr(10).join(bullets)}

## Skills Demonstrated

- Sovereign architecture design (31-board organism, K8s, GCP, Docker)
- Compiler engineering (FlameLang, Mobius DSL, lexer/parser/AST pipeline)
- Security engineering (antibody system, ERU loop, invariant enforcement)
- ERU methodology (Expected→Reality→Variance→Understanding→Antibody)
- Self-improving systems (BOARD-26 remediation loop, PMI scoring, invention pipeline)

---
*Generated by BOARD-32-PORTFOLIO-PUBLISHER — SAGCO-OS*
"""


# ── Index renderer ────────────────────────────────────────────────────────────

def render_index(case_files: list[Path], resume_files: list[Path],
                 inventions: list, antibodies: list) -> str:
    case_links  = "\n".join(f"- [{f.stem}](case-studies/{f.name})" for f in sorted(case_files))
    resume_links= "\n".join(f"- [{f.stem}](resume-bullets/{f.name})" for f in sorted(resume_files))

    return f"""# SAGCO-OS Portfolio

**Domenic Garza — Node 137**
**Strategickhaos DAO LLC**
**Generated:** {NOW}

## What This Is

SAGCO-OS is a 31-board sovereign architecture operating system built from
scratch: compiler, phone OS, security antibody library, GKE cluster, ERU
physics engine, Mobius calculus compiler, and a self-improving invention pipeline.

Every contradiction becomes a seed. Every seed becomes a case.
Every closed case is a proof. Every proof becomes a portfolio artifact.

## Metrics

| Metric | Count |
|--------|-------|
| Boards | 31 |
| Antibodies | {len(antibodies)} |
| Invention Seeds | {len(inventions)} |
| Districts | 8 |

## Case Studies

{case_links or '- (run `sagco portfolio build` to generate)'}

## Resume Bullets

{resume_links or '- (run `sagco portfolio build` to generate)'}

## Architecture

```
MISSING-LINKS  ← substrate (contradictions, gaps, orphans)
    ↓
BOARD-26       ← remediation (case → remediate → verify)
    ↓
BOARD-10       ← university (exam + grade + certify)
    ↓
BOARD-32       ← portfolio (harvest → render → publish)
```

## Key Inventions

{chr(10).join(f"- **{s.get('title','?')}** — {s.get('law','')}" for s in inventions) or '- (none yet closed)'}

---
*Generated by BOARD-32-PORTFOLIO-PUBLISHER — SAGCO-OS*
"""


# ── Main builder ──────────────────────────────────────────────────────────────

def build_all(only: str = "all"):
    OUT_CASES.mkdir(parents=True, exist_ok=True)
    OUT_RESUME.mkdir(parents=True, exist_ok=True)
    OUT_RPT.mkdir(parents=True, exist_ok=True)

    inventions = harvest_inventions()
    eru_cases  = harvest_eru_cases()
    certs      = harvest_certs()
    antibodies = harvest_antibodies()
    boards     = [str(d.name) for d in REPO_ROOT.iterdir()
                  if d.is_dir() and d.name.startswith("BOARD-")]

    case_files: list[Path] = []

    if only in ("all", "case-studies"):
        # Invention case studies
        for seed in inventions:
            slug = seed.get("seed_id", seed.get("title", "unknown")).replace(" ", "_").replace("/", "-")
            out  = OUT_CASES / f"{slug}.md"
            out.write_text(render_invention_case_study(seed))
            case_files.append(out)
            print(f"  case-study → {out.relative_to(REPO_ROOT)}")

        # ERU case studies
        seen_slugs: dict[str, int] = {}
        for case in eru_cases[:6]:  # top 6
            base_slug = (case.get("case_id") or case.get("title") or "eru_case").replace(" ", "_").replace("/", "-")
            seen_slugs[base_slug] = seen_slugs.get(base_slug, 0) + 1
            slug = base_slug if seen_slugs[base_slug] == 1 else f"{base_slug}_{seen_slugs[base_slug]}"
            out  = OUT_CASES / f"{slug}.md"
            out.write_text(render_gke_case_study(case))
            case_files.append(out)
            print(f"  case-study → {out.relative_to(REPO_ROOT)}")

    resume_files: list[Path] = []
    if only in ("all", "resume"):
        out = OUT_RESUME / "distinguished_engineer_bullets.md"
        out.write_text(render_resume_bullets(inventions, certs, antibodies, boards))
        resume_files.append(out)
        print(f"  resume    → {out.relative_to(REPO_ROOT)}")

    if only in ("all", "index"):
        index_out = BOARD / "portfolio_index.md"
        index_out.write_text(render_index(case_files, resume_files, inventions, antibodies))
        print(f"  index     → {index_out.relative_to(REPO_ROOT)}")

    # Inventory report
    inventory = {
        "generated": NOW,
        "inventions": len(inventions),
        "eru_cases": len(eru_cases),
        "certs": len(certs),
        "antibodies": len(antibodies),
        "boards": len(boards),
        "case_studies_rendered": len(case_files),
        "resume_bullets_rendered": len(resume_files),
    }
    (OUT_RPT / "portfolio_inventory.yaml").write_text(yaml.dump(inventory, sort_keys=False))
    print(f"\n  Portfolio built — {len(case_files)} case studies, {len(resume_files)} resume docs")


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--build",        action="store_true")
    ap.add_argument("--case-studies", action="store_true")
    ap.add_argument("--resume",       action="store_true")
    ap.add_argument("--index",        action="store_true")
    ap.add_argument("--list",         action="store_true")
    args = ap.parse_args()

    if args.list:
        print(f"\n  Inventions  : {len(harvest_inventions())}")
        print(f"  ERU cases   : {len(harvest_eru_cases())}")
        print(f"  Certs       : {len(harvest_certs())}")
        print(f"  Antibodies  : {len(harvest_antibodies())}")
        return

    if args.build or not any(vars(args).values()):
        build_all("all")
    elif args.case_studies:
        build_all("case-studies")
    elif args.resume:
        build_all("resume")
    elif args.index:
        build_all("index")


if __name__ == "__main__":
    main()
