#!/usr/bin/env python3
"""
FlameLang to LLVM Compiler Backend
Converts FlameLang glyph syntax to LLVM IR

Copyright (C) 2025 Strategickhaos DAO LLC
License: MIT
"""

import sys
import json
import re
from typing import Dict, List

class FlameLangLLVMCompiler:
    """Compile FlameLang glyph syntax to LLVM IR"""
    
    def __init__(self, glyph_map_path: str):
        """Initialize compiler with glyph map"""
        with open(glyph_map_path, 'r') as f:
            self.glyph_map = json.load(f)
        
        self.ir_buffer = []
        self.string_literals = []
        
    def emit_header(self):
        """Emit LLVM IR header"""
        self.ir_buffer.append('; FlameLang LLVM IR')
        self.ir_buffer.append('; Generated by flamelang_to_llvm.py')
        self.ir_buffer.append('; Target: x86_64-pc-linux-gnu')
        self.ir_buffer.append('')
        self.ir_buffer.append('target triple = "x86_64-pc-linux-gnu"')
        self.ir_buffer.append('')
        
    def emit_string_declaration(self, idx: int, content: str) -> str:
        """Emit global string constant"""
        escaped = content.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
        length = len(content) + 1
        var_name = f'@.str.{idx}'
        
        self.ir_buffer.append(
            f'{var_name} = private unnamed_addr constant [{length} x i8] c"{escaped}\\00", align 1'
        )
        return var_name
        
    def compile_glyph(self, glyph_expr: str) -> str:
        """Compile a glyph expression to LLVM function"""
        # Extract glyph pattern: {namespace⟐modifier}
        if glyph_expr.startswith('{') and glyph_expr.endswith('}'):
            glyph_key = glyph_expr
        else:
            raise ValueError(f"Invalid glyph syntax: {glyph_expr}")
        
        # Look up target executable
        if glyph_key not in self.glyph_map:
            raise ValueError(f"Unknown glyph: {glyph_key}")
        
        target_path = self.glyph_map[glyph_key]
        
        # Generate LLVM IR function that calls the target
        func_name = glyph_key.replace('{', '').replace('}', '').replace('⟐', '_')
        func_name = re.sub(r'[^a-zA-Z0-9_]', '_', func_name)
        
        self.ir_buffer.append(f'; Glyph: {glyph_key} -> {target_path}')
        self.ir_buffer.append(f'define i32 @flamelang_{func_name}() {{')
        self.ir_buffer.append('entry:')
        
        # Emit system() call to execute target
        str_idx = len(self.string_literals)
        str_var = self.emit_string_declaration(str_idx, target_path)
        self.string_literals.append(target_path)
        
        path_len = len(target_path) + 1
        self.ir_buffer.append(f'  %1 = call i32 @system(i8* getelementptr inbounds ([{path_len} x i8], [{path_len} x i8]* {str_var}, i64 0, i64 0))')
        self.ir_buffer.append('  ret i32 %1')
        self.ir_buffer.append('}')
        self.ir_buffer.append('')
        
        return func_name
        
    def emit_main(self, glyph_functions: List[str]):
        """Emit main function that calls all glyphs"""
        self.ir_buffer.append('define i32 @main() {')
        self.ir_buffer.append('entry:')
        
        for i, func in enumerate(glyph_functions):
            self.ir_buffer.append(f'  %result_{i} = call i32 @flamelang_{func}()')
        
        self.ir_buffer.append('  ret i32 0')
        self.ir_buffer.append('}')
        self.ir_buffer.append('')
        
    def emit_declarations(self):
        """Emit external function declarations"""
        self.ir_buffer.append('; External function declarations')
        self.ir_buffer.append('declare i32 @system(i8*)')
        self.ir_buffer.append('')
        
    def compile(self, glyph_exprs: List[str]) -> str:
        """Compile list of glyph expressions to LLVM IR"""
        self.emit_header()
        self.emit_declarations()
        
        glyph_functions = []
        for glyph in glyph_exprs:
            func_name = self.compile_glyph(glyph)
            glyph_functions.append(func_name)
        
        self.emit_main(glyph_functions)
        
        return '\n'.join(self.ir_buffer)


def main():
    """Main compiler entry point"""
    if len(sys.argv) < 3:
        print("Usage: flamelang_to_llvm.py <glyph_map.json> <input.flame>")
        print("")
        print("Example:")
        print("  flamelang_to_llvm.py glyph_map.json source.flame")
        print("")
        sys.exit(1)
    
    glyph_map_path = sys.argv[1]
    input_path = sys.argv[2]
    
    try:
        # Read input file
        with open(input_path, 'r') as f:
            glyph_exprs = [line.strip() for line in f if line.strip() and not line.strip().startswith('#')]
        
        # Compile
        compiler = FlameLangLLVMCompiler(glyph_map_path)
        ir_code = compiler.compile(glyph_exprs)
        
        # Write output
        output_path = input_path.replace('.flame', '.ll')
        with open(output_path, 'w') as f:
            f.write(ir_code)
        
        print(f"✅ Compiled {input_path} -> {output_path}")
        print(f"   Generated {len(compiler.string_literals)} string literals")
        print(f"   Generated {len(glyph_exprs)} glyph functions")
        
        # Optionally compile to object file with LLVM
        import subprocess
        try:
            subprocess.run(['llc', '-filetype=obj', output_path, '-o', output_path.replace('.ll', '.o')], check=True)
            print(f"✅ Generated object file: {output_path.replace('.ll', '.o')}")
        except (subprocess.CalledProcessError, FileNotFoundError):
            print("⚠️  LLVM not found, skipping object file generation")
    
    except FileNotFoundError as e:
        print(f"❌ Error: {e}")
        sys.exit(1)
    except ValueError as e:
        print(f"❌ Compilation error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
