// Example generated C code from FlameLang compiler
// This shows what the FlameLang compiler would generate
// when compiling example.flm

#include "../include/hv_api.h"
#include <stdio.h>
#include <stdlib.h>

int main() {
    printf("🔥 SAGCO Hypervisor Controller - Generated by FlameLang\n\n");
    
    // Initialize hypervisor subsystem
    hv_result_t result = hv_init();
    if (result != HV_OK) {
        fprintf(stderr, "Failed to initialize hypervisor\n");
        return 1;
    }
    
    // Create VM: sagco_live_1
    hv_vm_config_t cfg1;
    cfg1.name        = "sagco_live_1";
    cfg1.disk_path   = "/isos/sagco-live.iso";
    cfg1.kernel_path = "/boot/vmlinuz-sagco";
    cfg1.cmdline     = "root=/dev/vda console=ttyS0";
    cfg1.mem_mb      = 1024;
    cfg1.vcpus       = 2;
    cfg1.flags       = 0;
    
    result = hv_create_vm(&cfg1);
    if (result != HV_OK) {
        fprintf(stderr, "Failed to create VM: sagco_live_1\n");
        hv_shutdown();
        return 1;
    }
    
    // Create VM: test_vm
    hv_vm_config_t cfg2;
    cfg2.name        = "test_vm";
    cfg2.disk_path   = "/isos/alpine-virt.iso";
    cfg2.kernel_path = NULL;  // Optional
    cfg2.cmdline     = NULL;  // Optional
    cfg2.mem_mb      = 256;
    cfg2.vcpus       = 1;
    cfg2.flags       = 0;
    
    result = hv_create_vm(&cfg2);
    if (result != HV_OK) {
        fprintf(stderr, "Failed to create VM: test_vm\n");
        hv_shutdown();
        return 1;
    }
    
    // Boot command: start sagco_live_1
    result = hv_start_vm("sagco_live_1");
    if (result != HV_OK) {
        fprintf(stderr, "Failed to start VM: sagco_live_1\n");
        hv_shutdown();
        return 1;
    }
    
    printf("\n✅ All VMs configured and started successfully\n");
    printf("Press Enter to shutdown...\n");
    getchar();
    
    // Cleanup
    hv_stop_vm("sagco_live_1");
    hv_destroy_vm("sagco_live_1");
    hv_destroy_vm("test_vm");
    hv_shutdown();
    
    return 0;
}
