// Code Generator - Converts FlameIR to executable Rust code

use crate::ir::{FlameIR, FlameProgram};
use std::collections::HashMap;

pub struct CodeGenerator {
    output: String,
    indent: usize,
}

impl CodeGenerator {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
        }
    }
    
    fn emit(&mut self, code: &str) {
        let indent_str = "    ".repeat(self.indent);
        self.output.push_str(&format!("{}{}\n", indent_str, code));
    }
    
    fn indent(&mut self) {
        self.indent += 1;
    }
    
    fn dedent(&mut self) {
        if self.indent > 0 {
            self.indent -= 1;
        }
    }
    
    pub fn generate(&mut self, program: &FlameProgram) -> Result<String, String> {
        // Generate Rust code header
        self.emit("// Generated by FlameLang Compiler");
        self.emit("// KHAOS Script → FlameIR → Rust");
        self.emit("");
        self.emit("use std::collections::HashMap;");
        self.emit("");
        self.emit("fn main() {");
        self.indent();
        
        // Stack-based execution model
        self.emit("let mut stack: Vec<i64> = Vec::new();");
        self.emit("let mut vars: HashMap<String, i64> = HashMap::new();");
        self.emit("");
        
        // Generate code for each instruction
        for (idx, ir) in program.instructions.iter().enumerate() {
            self.emit(&format!("// Instruction {}: {:?}", idx, ir));
            match ir {
                FlameIR::LoadConst(n) => {
                    self.emit(&format!("stack.push({});", n));
                }
                FlameIR::LoadString(s) => {
                    // Strings are printed directly, not pushed to stack
                    self.emit(&format!("// String will be printed by next Print instruction"));
                    self.emit(&format!("stack.push(0); // Placeholder for string \"{}\"", s.replace('"', "\\\"")));
                    self.emit(&format!("stack.pop(); // Remove placeholder"));
                    self.emit(&format!("println!(\"{}\");", s.replace('"', "\\\"")));
                }
                FlameIR::Store(name) => {
                    self.emit(&format!("vars.insert(\"{}\".to_string(), stack.pop().unwrap());", name));
                }
                FlameIR::Load(name) => {
                    self.emit(&format!("stack.push(*vars.get(\"{}\").unwrap());", name));
                }
                FlameIR::Add => {
                    self.emit("let b = stack.pop().unwrap();");
                    self.emit("let a = stack.pop().unwrap();");
                    self.emit("stack.push(a + b);");
                }
                FlameIR::Sub => {
                    self.emit("let b = stack.pop().unwrap();");
                    self.emit("let a = stack.pop().unwrap();");
                    self.emit("stack.push(a - b);");
                }
                FlameIR::Mul => {
                    self.emit("let b = stack.pop().unwrap();");
                    self.emit("let a = stack.pop().unwrap();");
                    self.emit("stack.push(a * b);");
                }
                FlameIR::Div => {
                    self.emit("let b = stack.pop().unwrap();");
                    self.emit("let a = stack.pop().unwrap();");
                    self.emit("stack.push(a / b);");
                }
                FlameIR::Print => {
                    self.emit("if let Some(val) = stack.pop() {");
                    self.indent();
                    self.emit("println!(\"{}\", val);");
                    self.dedent();
                    self.emit("}");
                }
                FlameIR::Assert => {
                    self.emit("assert!(stack.pop().unwrap() != 0, \"Assertion failed\");");
                }
                FlameIR::Trig6Sin(angle) => {
                    let result = angle.to_radians().sin();
                    self.emit(&format!("stack.push({} as i64);", result));
                }
                FlameIR::Trig6Cos(angle) => {
                    let result = angle.to_radians().cos();
                    self.emit(&format!("stack.push({} as i64);", result));
                }
                FlameIR::Trig6Tan(angle) => {
                    let result = angle.to_radians().tan();
                    self.emit(&format!("stack.push({} as i64);", result));
                }
                FlameIR::Halt => {
                    self.emit("// Program halted");
                }
                _ => {
                    return Err(format!("Unsupported IR instruction: {:?}", ir));
                }
            }
        }
        
        self.dedent();
        self.emit("}");
        
        Ok(self.output.clone())
    }
}

impl Default for CodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_codegen_simple() {
        let mut program = FlameProgram::new();
        program.push(FlameIR::LoadConst(42));
        program.push(FlameIR::Print);
        program.push(FlameIR::Halt);
        
        let mut codegen = CodeGenerator::new();
        let result = codegen.generate(&program);
        
        assert!(result.is_ok());
        assert!(result.unwrap().contains("stack.push(42)"));
    }
}
