# Auto-generated by BOARD-31 compiler.py
# DO NOT EDIT — regenerate with: python src/compiler.py

def test_token_in_url(event: dict) -> bool:
    # if(token_in_url) when(browser_nav) then(fire_antibody BROWSER_TOKEN_IN_REFERRER)
    from src.compiler import _eval_condition
    cond = _eval_condition('token_in_url', event)
    trig = _eval_condition('browser_nav', event) if 'browser_nav' != 'always' else True
    return cond and trig
